### ISSUE TITLE
Cjdns fails to build on Raspberry Pi 2

### ISSUE THREAD

**Issue by Shnatsel** [hyperboria/cjdns#88] opened 2015-11-28 02:41 UTC
It appears to be failing on "Running test EncodingScheme_testTIMEOUT" and builds successfully with "NO_TEST=1".

Full build log: http://pastebin.ubuntu.com/13536784/

Tested on master from https://github.com/cjdelisle/cjdns/, RPi 2, Raspbian Jessie

**Comment by koalalorenzo** [comment] 2015-12-03 07:26
Same problem for me!
This is my output: http://pastebin.com/YmwZ2L9p

**Comment by koalalorenzo** [comment] 2015-12-05 18:43
I still can't access, but apparently cjdns was compiled for ARMv7 and it is working with http://archlinuxarm.org/

Probably some dependencies are missing or some libraries are not updated.

**Comment by koalalorenzo** [comment] 2015-12-05 20:00
I have been trying to build it using gcc 4.7, 4.8 and 4.9. on All of them it seems to fail for a timeout during testing. Still using Raspbian Jessie. 

I have also tried with "./cross-do", it compiles but it is not able to connect returning this error: http://pastebin.com/akKwNJtp

I really would like to understand how to get cjdns on Raspbian Jessie, for Raspberry Pi 2 (ARMv7) since other distribution were able to.

**Comment by koalalorenzo** [comment] 2015-12-05 20:02
It seems to be related to #6

**Comment by Shnatsel** [comment] 2015-12-05 20:10
NO_TEST=1 Seccomp_NO=1 ./do

this works as a temporary workaround for both this issue and #6

**Comment by Kubuxu** [comment] 2015-12-05 20:13
Can someone of  you show result of 
```
sudo zcat /proc/config.gz | grep CONFIG_SECCOMP_FILTER
```
and also `uname -a`.

**Comment by Shnatsel** [comment] 2015-12-05 20:19
$ sudo zcat /proc/config.gz
    gzip: /proc/config.gz: No such file or directory

    $ uname -a
    Linux raspberrypi 4.1.12-v7+ #824 SMP PREEMPT Wed Oct 28 16:46:35 GMT 2015 armv7l GNU/Linux

If you find any way to get the kernel config on Raspberry Pi please let me know, because we also need it for #6

**Comment by Kubuxu** [comment] 2015-12-05 20:22
It might be also in `/boot/`. If not then manual kernel compilation guide.

**Comment by Kubuxu** [comment] 2015-12-05 20:32
Here is the config: https://github.com/raspberrypi/linux/blob/rpi-4.1.y/arch/arm/configs/bcm2709_defconfig

**Comment by Shnatsel** [comment] 2015-12-05 20:32
There is /boot/config.txt but it's not kernel configuration, it's this: https://ncry.pt/p/YpBn#HpPNrZgtWJm-cTL4rc1jFmGDY1_UcfPPtUSnP7mVFq8

**Comment by Kubuxu** [comment] 2015-12-05 20:36
It is duplicate of #6 it should be closed on a benefit of older issue.

**Comment by Shnatsel** [comment] 2015-12-05 20:39
No. #6 is about SECCOMP failing, this is about a timed test failing. It still fails if I disable SECCOMP but leave tests enabled.

**Comment by Shnatsel** [comment] 2015-12-05 20:55
Actually, build still fails with ./clean Seccomp_NO=1 ./do, so this is a dupe of #6 after all. My bad.

**Comment by koalalorenzo** [comment] 2015-12-06 07:51
So, It will compile and it seems to work correctly (even the tests) by  running ```Seccomp_NO=1 ./do```

I will probably take care of another guide, suggesting to recompile the kernel to enble the feature.

**Comment by koalalorenzo** [comment] 2015-12-06 07:52
I agree with @Kubuxu we should probably close this and report in the other Issue

**Comment by Kubuxu** [comment] 2016-01-19 07:09
Copy of #6.

**Closed by Kubuxu** 2016-01-19 07:09 UTC
